### PR TITLE
Support laravel 5

### PR DESCRIPTION
**Pull request by tbleckert**
Works without problem as it seems, just changed the version to 5.0.*

### CODE REVIEW

**Comment by tbleckert** [comment]
This fixes #17

**Comment by barryvdh** [comment]
Better change it to `4.*|5.0.*` so you can support both versions.

**Comment by tbleckert** [comment]
Yeah that's true @barryvdh , thanks and it's now updated.

**Comment by vinkla** [comment]
This can be closed in favor of #22. Since it won't work when @laravel 5 is stable due to new way to publish package config.

**Pull request closed without merging**
